# Generated by Django 3.1.7 on 2021-04-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Text',
            new_name='text',
        ),
    ]
